import { useState, useRef, useEffect } from "react";
import { Group, Panel, Separator } from "react-resizable-panels";
import * as monaco from "monaco-editor";
import { useVMEmulator } from "../hooks/useVMEmulator";
import { DebuggerCodeDisplay } from "../components/Emulator/DebuggerCodeDisplay";
import { RamViewer } from "../components/Emulator/RamViewer";
import { EmulatorScreen } from "../components/Emulator/EmulatorScreen";
import { type VirtualFile } from "../types/Vfs";

const DEFAULT_VM_CODE = `// Simple VM Example
push constant 7
push constant 8
add
pop temp 0
`;

function VMStatePanel({ 
  pc, 
  basePointers, 
  callStack 
}: { 
  pc: number, 
  basePointers: Record<string, number>, 
  callStack: string[] 
}) {
  return (
    <div className="bg-slate-950 border border-slate-800 rounded p-4 flex flex-col gap-4">
      <h3 className="text-sm font-semibold text-slate-300 uppercase tracking-wider">VM State</h3>
      
      <div className="grid grid-cols-2 gap-4">
        {/* Base Pointers */}
        <div className="flex flex-col gap-2">
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">PC</span>
            <span className="font-mono text-indigo-400">{pc}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">SP</span>
            <span className="font-mono text-emerald-400">{basePointers.sp}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">LCL</span>
            <span className="font-mono text-amber-400">{basePointers.lcl}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">ARG</span>
            <span className="font-mono text-blue-400">{basePointers.arg}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">THIS</span>
            <span className="font-mono text-purple-400">{basePointers.this}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span className="text-slate-500">THAT</span>
            <span className="font-mono text-pink-400">{basePointers.that}</span>
          </div>
        </div>

        {/* Call Stack */}
        <div className="flex flex-col gap-2 border-l border-slate-800 pl-4">
          <span className="text-xs text-slate-500 uppercase">Call Stack</span>
          <div className="flex-1 bg-slate-900 rounded p-2 overflow-y-auto min-h-[100px] font-mono text-xs text-slate-300">
            {callStack.length === 0 ? (
              <span className="text-slate-600 italic">Empty</span>
            ) : (
              callStack.map((func, i) => (
                <div key={i} className="py-0.5 flex gap-2">
                  <span className="text-slate-600">[{i}]</span>
                  <span className="text-teal-400">{func}</span>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

export function VMEmulatorPage() {
  const { 
    pc, 
    basePointers, 
    callStack, 
    load, 
    clearRam, 
    step, 
    getRamRange, 
    getSourceMap,
    setRam, 
    isRunning, 
    setIsRunning, 
    speed, 
    setSpeed, 
    frameCount 
  } = useVMEmulator();

  const [source, setSource] = useState(DEFAULT_VM_CODE);
  
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);
  const decorationCollectionRef = useRef<monaco.editor.IEditorDecorationsCollection | null>(null);
  
  // Note: To get line highlighting working properly, your VMEmulator needs to expose 
  // the sourceMap generated by VMParser. You can add this to useVMEmulator later!
  const sourceMapRef = useRef<number[]>([]);

  const handleLoad = () => {
    try {
      const file: VirtualFile = {
        id: 'editor-file',
        name: 'Main.vm',
        language: 'vm',
        content: source
      };
      
      load([file], false); // Pass false to allow auto-bootstrap if Sys.init is found
      
      sourceMapRef.current = getSourceMap() as number[]; 

    } catch (e) {
      console.error("VM load error:", e);
      alert("Failed to parse VM code. Check console for details.");
    }
  };

  useEffect(() => {
    const editor = editorRef.current;
    const lineNumber = sourceMapRef.current[pc];

    if (editor && lineNumber) {
      if (!decorationCollectionRef.current) {
        decorationCollectionRef.current = editor.createDecorationsCollection();
      }

      decorationCollectionRef.current.set([
        {
          range: new monaco.Range(lineNumber, 1, lineNumber, 1),
          options: {
            isWholeLine: true,
            className: 'asm-line-highlight',
          },
        },
      ]);
      
      editor.revealLineInCenter(lineNumber);
    }
  }, [pc]);

  return (
    <div className="h-full w-full bg-slate-900 text-slate-100 flex flex-col">
      {/* Toolbar */}
      <div className="h-12 border-b border-slate-800 flex items-center px-4 gap-2 bg-slate-950">
        <button 
          onClick={handleLoad} 
          className="px-3 py-1 bg-indigo-600 hover:bg-indigo-500 rounded text-sm font-medium transition-colors"
        >
          Load Program
        </button>
        <button 
          onClick={step} 
          className="px-3 py-1 bg-slate-700 hover:bg-slate-600 rounded text-sm font-medium transition-colors"
        >
          Step
        </button>

        <button 
          onClick={() => setIsRunning(!isRunning)} 
          className={`px-3 py-1 rounded text-sm font-medium ${isRunning ? 'bg-red-600 hover:bg-red-500' : 'bg-emerald-600 hover:bg-emerald-500'}`}
        >
          {isRunning ? "Stop" : "Run"}
        </button>

        <div className="flex items-center gap-2 text-xs text-slate-400">
          <span>Speed:</span>
          <input 
            type="range" 
            min="1" 
            max="100" 
            value={speed} 
            onChange={(e) => setSpeed(Number(e.target.value))}
            className="w-24 accent-indigo-500"
          />
        </div>
      </div>

      <Group className="flex-1">
        {/* Left: Code Editor */}
        <Panel defaultSize={40}>
          <DebuggerCodeDisplay 
            title="VM Code"
            language="hackvm"
            value={source}
            onChange={setSource}
            pc={pc}
            sourceMap={sourceMapRef.current}
            errors={[]}
          />
        </Panel>

        <Separator className="w-1 bg-slate-800" />

        {/* Center: Screen & VM State */}
        <Panel defaultSize={30} className="p-4 flex flex-col gap-4">
          {/* Screen at the top */}
          <div className="bg-slate-950 rounded border border-slate-800 p-1">
            <EmulatorScreen 
              getRamRange={getRamRange}
              frameCount={frameCount}
            />
          </div>

          {/* VM State pinned below the screen */}
          <VMStatePanel 
            pc={pc} 
            basePointers={basePointers} 
            callStack={callStack} 
          />
          
          <div className="flex-1" />
        </Panel>

        <Separator className="w-1 bg-slate-800" />

        {/* Right: RAM Viewer */}
        <Panel defaultSize={30}>
          <RamViewer getRamRange={getRamRange} setRam={setRam} clearRam={clearRam} />
        </Panel>
      </Group>
    </div>
  );
}